name: Sweep

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  sweep:
    name: Sweep
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Sweep
        uses: sweepai/sweep@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
